//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 2016 by Gareth Nelson (gareth@garethnelson.com)
//
// This file is part of the Lambda engine.
//
// The Lambda engine is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
//
// The Lambda engine is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
//
// $Log:$
//
// DESCRIPTION:
//     Game logic for map02 in the sample game
//
//-----------------------------------------------------------------------------

// The below is mostly standard boilerplate for any map

#include <map02/mapinfo.h>
#include <map02/hotzone.h>
#include <map02/collision.h>
#include <map02/entities.h>
#include <lambda_api.h>

// Called by the hook when the player presses action near the button
void map02_ent_button_action_handler(void* param) {
     lambda_switch_map("map01");
}

// This function is called when the map is loaded
// It is intended for configuration of hooks, do not put rendering code in here
void map02_init() {
     // The ent_player class is part of the engine, so these handlers are generated automatically
     SET_SINGLE_HOOK(input_up,           &map02_ent_player_up_handler);
     SET_SINGLE_HOOK(input_down,         &map02_ent_player_down_handler);
     SET_SINGLE_HOOK(input_left,         &map02_ent_player_left_handler);
     SET_SINGLE_HOOK(input_right,        &map02_ent_player_right_handler);

     // The hook is generated by the map compiler, but not the handler
     // This hook is activated any time the action button is pressed near ent_button
     SET_SINGLE_HOOK(map02_ent_button_action, &map02_ent_button_action_handler);
}

// This is a cleanup function called before the next map is loaded
void map02_finish() {
     // this stuff is not strictly necessary, but a good idea
     IMPORT(i_default)
     SET_SINGLE_HOOK(input_up,    &i_default);
     SET_SINGLE_HOOK(input_down,  &i_default);
     SET_SINGLE_HOOK(input_left,  &i_default);
     SET_SINGLE_HOOK(input_right, &i_default);
}

